"""ajustes de campos de datas

Revision ID: 327249154b7b
Revises: ec2b2d47ce7a
Create Date: 2026-04-22 15:28:01.413214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '327249154b7b'
down_revision: Union[str, Sequence[str], None] = 'ec2b2d47ce7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_errors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False))
    op.add_column('task_errors', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False))
    op.add_column('task_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False))
    op.add_column('task_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False))
    op.add_column('task_parameters', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False))
    op.add_column('task_parameters', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False))
    op.add_column('task_telemetries', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False))
    op.add_column('worker_runtime_events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False))
    op.drop_index(op.f('ix_worker_runtime_events_created_at'), table_name='worker_runtime_events')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_worker_runtime_events_created_at'), 'worker_runtime_events', ['created_at'], unique=False)
    op.drop_column('worker_runtime_events', 'updated_at')
    op.drop_column('tasks', 'updated_at')
    op.drop_column('task_telemetries', 'updated_at')
    op.drop_column('task_parameters', 'updated_at')
    op.drop_column('task_parameters', 'created_at')
    op.drop_column('task_logs', 'updated_at')
    op.drop_column('task_logs', 'created_at')
    op.drop_column('task_errors', 'updated_at')
    op.drop_column('task_errors', 'created_at')
    # ### end Alembic commands ###
