"""add checksum and is_active to bot_versions

Revision ID: 32faa1309976
Revises: 05a6b64d45a3
Create Date: 2026-03-24 16:25:23.025920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32faa1309976'
down_revision: Union[str, Sequence[str], None] = '05a6b64d45a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_versions', sa.Column('checksum', sa.String(length=255), nullable=True))
    op.add_column('bot_versions', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_versions', 'is_active')
    op.drop_column('bot_versions', 'checksum')
    # ### end Alembic commands ###
