"""add runner_status_history

Revision ID: 40af40d590b3
Revises: 327249154b7b
Create Date: 2026-04-22 15:52:16.807247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40af40d590b3'
down_revision: Union[str, Sequence[str], None] = '327249154b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runner_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], name=op.f('fk_runner_status_history_runner_id_runners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runner_status_history'))
    )
    op.create_index(op.f('ix_runner_status_history_created_at'), 'runner_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_runner_status_history_id'), 'runner_status_history', ['id'], unique=False)
    op.create_index('ix_runner_status_history_runner_created', 'runner_status_history', ['runner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_runner_status_history_runner_id'), 'runner_status_history', ['runner_id'], unique=False)
    op.create_index('ix_runner_status_history_runner_status', 'runner_status_history', ['runner_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_runner_status_history_runner_status', table_name='runner_status_history')
    op.drop_index(op.f('ix_runner_status_history_runner_id'), table_name='runner_status_history')
    op.drop_index('ix_runner_status_history_runner_created', table_name='runner_status_history')
    op.drop_index(op.f('ix_runner_status_history_id'), table_name='runner_status_history')
    op.drop_index(op.f('ix_runner_status_history_created_at'), table_name='runner_status_history')
    op.drop_table('runner_status_history')
    # ### end Alembic commands ###
