"""add screenshot fields to runners

Revision ID: ec2b2d47ce7a
Revises: 48f716671eb2
Create Date: 2026-04-22 15:14:12.201515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'ec2b2d47ce7a'
down_revision: Union[str, Sequence[str], None] = '48f716671eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False))
    op.add_column('automation_parameters', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('sysdatetimeoffset()'), nullable=False))
    op.drop_column('automation_runners', 'created_at')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_column('permissions', 'created_at')
    op.add_column('runners', sa.Column('last_screenshot_image', sa.LargeBinary(), nullable=True))
    op.add_column('runners', sa.Column('last_screenshot_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_runners_last_screenshot_at'), 'runners', ['last_screenshot_at'], unique=False)
    op.drop_column('task_errors', 'created_at')
    op.drop_column('task_logs', 'created_at')
    op.drop_column('task_parameters', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_parameters', sa.Column('created_at', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False))
    op.add_column('task_logs', sa.Column('created_at', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False))
    op.add_column('task_errors', sa.Column('created_at', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_runners_last_screenshot_at'), table_name='runners')
    op.drop_column('runners', 'last_screenshot_at')
    op.drop_column('runners', 'last_screenshot_image')
    op.add_column('permissions', sa.Column('created_at', sa.DATETIME(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.add_column('automation_runners', sa.Column('created_at', mssql.DATETIMEOFFSET(), autoincrement=False, nullable=False))
    op.drop_column('automation_parameters', 'updated_at')
    op.drop_column('audit_logs', 'updated_at')
    # ### end Alembic commands ###
