"""fix bots remove bot_id

Revision ID: ee675d945755
Revises: d2fe89a1917e
Create Date: 2026-03-24 15:51:19.060117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee675d945755'
down_revision: Union[str, Sequence[str], None] = 'd2fe89a1917e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Remove o índice primeiro
    op.drop_index('ix_bots_bot_id', table_name='bots')

    # 2. Agora remove a coluna
    op.drop_column('bots', 'bot_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('bot_id', sa.VARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
