"""create initial orkaflow schema

Revision ID: f593523eef6b
Revises: 
Create Date: 2026-03-19 16:26:09.118871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = 'f593523eef6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repositories'))
    )
    op.create_index(op.f('ix_repositories_active'), 'repositories', ['active'], unique=False)
    op.create_index(op.f('ix_repositories_name'), 'repositories', ['name'], unique=True)
    op.create_table('runners',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('host_name', sa.String(length=150), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('os_name', sa.String(length=80), nullable=True),
    sa.Column('os_version', sa.String(length=80), nullable=True),
    sa.Column('cpu_arch', sa.String(length=50), nullable=True),
    sa.Column('memory_total', sa.BigInteger(), nullable=True),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'BUSY', 'MAINTENANCE', 'BLOCKED', name='runner_status'), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_remote', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runners'))
    )
    op.create_index(op.f('ix_runners_enabled'), 'runners', ['enabled'], unique=False)
    op.create_index(op.f('ix_runners_last_heartbeat'), 'runners', ['last_heartbeat'], unique=False)
    op.create_index(op.f('ix_runners_name'), 'runners', ['name'], unique=True)
    op.create_index(op.f('ix_runners_status'), 'runners', ['status'], unique=False)
    op.create_index(op.f('ix_runners_uuid'), 'runners', ['uuid'], unique=True)
    op.create_table('users',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('login', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_active'), 'users', ['active'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('bots',
    sa.Column('bot_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('technology', sa.Enum('PYTHON', 'JAVA', 'NODE', 'POWERSHELL', 'OTHER', name='bot_technology'), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('current_version', sa.String(length=50), nullable=True),
    sa.Column('release_version', sa.String(length=50), nullable=True),
    sa.Column('source_type', sa.Enum('GIT', 'ARTIFACT', 'ZIP', 'MANUAL', name='bot_source_type'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('entrypoint', sa.String(length=255), nullable=False),
    sa.Column('requirements_file', sa.String(length=255), nullable=True),
    sa.Column('timeout_default', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_bots_repository_id_repositories'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bots')),
    sa.UniqueConstraint('repository_id', 'name', name='uq_bots_repository_id_name')
    )
    op.create_index(op.f('ix_bots_active'), 'bots', ['active'], unique=False)
    op.create_index(op.f('ix_bots_bot_id'), 'bots', ['bot_id'], unique=True)
    op.create_index(op.f('ix_bots_name'), 'bots', ['name'], unique=False)
    op.create_index(op.f('ix_bots_repository_id'), 'bots', ['repository_id'], unique=False)
    op.create_table('credentials',
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_credentials_repository_id_repositories'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials')),
    sa.UniqueConstraint('repository_id', 'label', name='uq_credentials_repository_id_label')
    )
    op.create_index(op.f('ix_credentials_active'), 'credentials', ['active'], unique=False)
    op.create_index(op.f('ix_credentials_repository_id'), 'credentials', ['repository_id'], unique=False)
    op.create_table('runner_configs',
    sa.Column('runner_id', sa.Integer(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('allowed_parallel_bots', mssql.JSON(), nullable=True),
    sa.Column('polling_interval', sa.Integer(), nullable=False),
    sa.Column('auto_update_bots', sa.Boolean(), nullable=False),
    sa.Column('install_all_bots_on_register', sa.Boolean(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], name=op.f('fk_runner_configs_runner_id_runners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runner_configs'))
    )
    op.create_index(op.f('ix_runner_configs_runner_id'), 'runner_configs', ['runner_id'], unique=True)
    op.create_table('automations',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('default_priority', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('EMAIL', 'PANEL', 'WEBHOOK', name='notification_type'), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_automations_bot_id_bots'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_automations_repository_id_repositories'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automations')),
    sa.UniqueConstraint('repository_id', 'name', name='uq_automations_repository_id_name')
    )
    op.create_index(op.f('ix_automations_active'), 'automations', ['active'], unique=False)
    op.create_index(op.f('ix_automations_bot_id'), 'automations', ['bot_id'], unique=False)
    op.create_index(op.f('ix_automations_name'), 'automations', ['name'], unique=False)
    op.create_index(op.f('ix_automations_repository_id'), 'automations', ['repository_id'], unique=False)
    op.create_table('bot_versions',
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('commit_hash', sa.String(length=80), nullable=True),
    sa.Column('branch', sa.String(length=120), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name=op.f('fk_bot_versions_bot_id_bots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bot_versions_created_by_users'), ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bot_versions')),
    sa.UniqueConstraint('bot_id', 'version', name='uq_bot_versions_bot_id_version')
    )
    op.create_index(op.f('ix_bot_versions_bot_id'), 'bot_versions', ['bot_id'], unique=False)
    op.create_index(op.f('ix_bot_versions_created_by'), 'bot_versions', ['created_by'], unique=False)
    op.create_table('credential_items',
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=120), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Enum('STRING', 'PASSWORD', 'TOKEN', 'JSON', 'SECRET', name='credential_value_type'), nullable=False),
    sa.Column('masked_preview', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], name=op.f('fk_credential_items_credential_id_credentials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credential_items')),
    sa.UniqueConstraint('credential_id', 'key_name', name='uq_credential_items_credential_id_key_name')
    )
    op.create_index(op.f('ix_credential_items_credential_id'), 'credential_items', ['credential_id'], unique=False)
    op.create_table('automation_parameters',
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('STRING', 'INTEGER', 'FLOAT', 'BOOLEAN', 'DATETIME', 'JSON', 'SELECT', 'SECRET_REF', name='parameter_type'), nullable=False),
    sa.Column('allowed_values', mssql.JSON(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], name=op.f('fk_automation_parameters_automation_id_automations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_parameters')),
    sa.UniqueConstraint('automation_id', 'name', name='uq_automation_parameters_automation_id_name')
    )
    op.create_index(op.f('ix_automation_parameters_automation_id'), 'automation_parameters', ['automation_id'], unique=False)
    op.create_table('automation_runners',
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], name=op.f('fk_automation_runners_automation_id_automations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], name=op.f('fk_automation_runners_runner_id_runners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_runners')),
    sa.UniqueConstraint('automation_id', 'runner_id', name='uq_automation_runners_automation_id_runner_id')
    )
    op.create_index(op.f('ix_automation_runners_automation_id'), 'automation_runners', ['automation_id'], unique=False)
    op.create_index(op.f('ix_automation_runners_runner_id'), 'automation_runners', ['runner_id'], unique=False)
    op.create_table('notifications',
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('EMAIL', 'PANEL', 'WEBHOOK', name='notification_channel_type'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], name=op.f('fk_notifications_automation_id_automations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('automation_id', 'user_id', 'notification_type', name='uq_notifications_automation_id_user_id_notification_type')
    )
    op.create_index(op.f('ix_notifications_active'), 'notifications', ['active'], unique=False)
    op.create_index(op.f('ix_notifications_automation_id'), 'notifications', ['automation_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('schedules',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('schedule_type', sa.Enum('CALENDAR', 'CRON', name='schedule_type'), nullable=False),
    sa.Column('calendar_type', sa.Enum('ONCE', 'SECOND', 'MINUTE', 'HOUR', 'DAY', 'WEEK', 'MONTH', name='calendar_type'), nullable=True),
    sa.Column('cron_expression', sa.String(length=120), nullable=True),
    sa.Column('policy', sa.Enum('CREATE_ALWAYS', 'IGNORE_IF_RUNNING', 'ENQUEUE_IF_NONE_PENDING', 'RUN_IF_MISSED', 'SKIP_IF_MISSED', name='schedule_policy'), nullable=False),
    sa.Column('parameters_json', mssql.JSON(), nullable=True),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PAUSED', 'ERROR', name='schedule_status'), nullable=False),
    sa.Column('interval_value', sa.Integer(), nullable=True),
    sa.Column('interval_unit', sa.String(length=30), nullable=True),
    sa.Column('misfire_policy', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], name=op.f('fk_schedules_automation_id_automations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedules'))
    )
    op.create_index(op.f('ix_schedules_active'), 'schedules', ['active'], unique=False)
    op.create_index(op.f('ix_schedules_automation_id'), 'schedules', ['automation_id'], unique=False)
    op.create_index(op.f('ix_schedules_name'), 'schedules', ['name'], unique=False)
    op.create_index(op.f('ix_schedules_next_run_at'), 'schedules', ['next_run_at'], unique=False)
    op.create_table('tasks',
    sa.Column('automation_id', sa.Integer(), nullable=False),
    sa.Column('bot_version_id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'SCHEDULED', 'READY', 'RUNNING', 'STOP_REQUESTED', 'CANCELED', 'FINISHED', 'ERROR', 'TIMEOUT', name='task_status'), nullable=False),
    sa.Column('requested_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_message', sa.Text(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('execution_mode', sa.Enum('MANUAL', 'SCHEDULED', 'RETRY', 'REPROCESS', 'API', name='execution_mode'), nullable=False),
    sa.Column('dispatch_attempts', sa.Integer(), nullable=False),
    sa.Column('stop_requested', sa.Boolean(), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('queue_name', sa.String(length=100), nullable=True),
    sa.Column('inactivity_timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('runner_claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], name=op.f('fk_tasks_automation_id_automations'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['bot_version_id'], ['bot_versions.id'], name=op.f('fk_tasks_bot_version_id_bot_versions'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_task_id'], ['tasks.id'], name=op.f('fk_tasks_parent_task_id_tasks'), ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], name=op.f('fk_tasks_runner_id_runners'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('fk_tasks_schedule_id_schedules'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_automation_id'), 'tasks', ['automation_id'], unique=False)
    op.create_index(op.f('ix_tasks_bot_version_id'), 'tasks', ['bot_version_id'], unique=False)
    op.create_index(op.f('ix_tasks_correlation_id'), 'tasks', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_by'), 'tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.create_index(op.f('ix_tasks_requested_start_at'), 'tasks', ['requested_start_at'], unique=False)
    op.create_index(op.f('ix_tasks_runner_id'), 'tasks', ['runner_id'], unique=False)
    op.create_index(op.f('ix_tasks_schedule_id'), 'tasks', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_tasks_started_at'), 'tasks', ['started_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('locks',
    sa.Column('lock_key', sa.String(length=150), nullable=False),
    sa.Column('scope_type', sa.Enum('RUNNER', 'AUTOMATION', 'BOT', 'EXTERNAL_SYSTEM', 'CREDENTIAL', 'BUSINESS_RESOURCE', name='lock_scope_type'), nullable=False),
    sa.Column('owner_task_id', sa.Integer(), nullable=False),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_task_id'], ['tasks.id'], name=op.f('fk_locks_owner_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], name=op.f('fk_locks_runner_id_runners'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locks'))
    )
    op.create_index(op.f('ix_locks_active'), 'locks', ['active'], unique=False)
    op.create_index(op.f('ix_locks_expires_at'), 'locks', ['expires_at'], unique=False)
    op.create_index(op.f('ix_locks_lock_key'), 'locks', ['lock_key'], unique=False)
    op.create_index(op.f('ix_locks_owner_task_id'), 'locks', ['owner_task_id'], unique=False)
    op.create_index(op.f('ix_locks_runner_id'), 'locks', ['runner_id'], unique=False)
    op.create_index(op.f('ix_locks_scope_type'), 'locks', ['scope_type'], unique=False)
    op.create_table('task_errors',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stacktrace', sa.Text(), nullable=True),
    sa.Column('error_category', sa.Enum('TECHNICAL', 'BUSINESS', 'TIMEOUT', 'LOCK', 'VALIDATION', 'DEPENDENCY', 'NETWORK', name='error_category'), nullable=True),
    sa.Column('is_retryable', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('WORKER', 'BACKEND', 'SCHEDULER', 'DISPATCHER', name='task_error_source'), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_errors_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_errors'))
    )
    op.create_index(op.f('ix_task_errors_error_type'), 'task_errors', ['error_type'], unique=False)
    op.create_index(op.f('ix_task_errors_task_id'), 'task_errors', ['task_id'], unique=False)
    op.create_table('task_logs',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='task_log_level'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('WORKER', 'BACKEND', 'SCHEDULER', 'DISPATCHER', name='task_log_source'), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('runner_id', sa.Integer(), nullable=True),
    sa.Column('event_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['runner_id'], ['runners.id'], name=op.f('fk_task_logs_runner_id_runners'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_logs_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_logs'))
    )
    op.create_index(op.f('ix_task_logs_level'), 'task_logs', ['level'], unique=False)
    op.create_index(op.f('ix_task_logs_task_id'), 'task_logs', ['task_id'], unique=False)
    op.create_table('task_parameters',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.String(length=100), nullable=False),
    sa.Column('parameter_value', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('resolved_from_credential_item_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resolved_from_credential_item_id'], ['credential_items.id'], name=op.f('fk_task_parameters_resolved_from_credential_item_id_credential_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_parameters_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_parameters'))
    )
    op.create_index(op.f('ix_task_parameters_task_id'), 'task_parameters', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_parameters_task_id'), table_name='task_parameters')
    op.drop_table('task_parameters')
    op.drop_index(op.f('ix_task_logs_task_id'), table_name='task_logs')
    op.drop_index(op.f('ix_task_logs_level'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_task_errors_task_id'), table_name='task_errors')
    op.drop_index(op.f('ix_task_errors_error_type'), table_name='task_errors')
    op.drop_table('task_errors')
    op.drop_index(op.f('ix_locks_scope_type'), table_name='locks')
    op.drop_index(op.f('ix_locks_runner_id'), table_name='locks')
    op.drop_index(op.f('ix_locks_owner_task_id'), table_name='locks')
    op.drop_index(op.f('ix_locks_lock_key'), table_name='locks')
    op.drop_index(op.f('ix_locks_expires_at'), table_name='locks')
    op.drop_index(op.f('ix_locks_active'), table_name='locks')
    op.drop_table('locks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_started_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_schedule_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_runner_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_requested_start_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_by'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_correlation_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_bot_version_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_automation_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_schedules_next_run_at'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_name'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_automation_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_active'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_automation_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_active'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_automation_runners_runner_id'), table_name='automation_runners')
    op.drop_index(op.f('ix_automation_runners_automation_id'), table_name='automation_runners')
    op.drop_table('automation_runners')
    op.drop_index(op.f('ix_automation_parameters_automation_id'), table_name='automation_parameters')
    op.drop_table('automation_parameters')
    op.drop_index(op.f('ix_credential_items_credential_id'), table_name='credential_items')
    op.drop_table('credential_items')
    op.drop_index(op.f('ix_bot_versions_created_by'), table_name='bot_versions')
    op.drop_index(op.f('ix_bot_versions_bot_id'), table_name='bot_versions')
    op.drop_table('bot_versions')
    op.drop_index(op.f('ix_automations_repository_id'), table_name='automations')
    op.drop_index(op.f('ix_automations_name'), table_name='automations')
    op.drop_index(op.f('ix_automations_bot_id'), table_name='automations')
    op.drop_index(op.f('ix_automations_active'), table_name='automations')
    op.drop_table('automations')
    op.drop_index(op.f('ix_runner_configs_runner_id'), table_name='runner_configs')
    op.drop_table('runner_configs')
    op.drop_index(op.f('ix_credentials_repository_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_active'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_bots_repository_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_name'), table_name='bots')
    op.drop_index(op.f('ix_bots_bot_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_active'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_active'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_runners_uuid'), table_name='runners')
    op.drop_index(op.f('ix_runners_status'), table_name='runners')
    op.drop_index(op.f('ix_runners_name'), table_name='runners')
    op.drop_index(op.f('ix_runners_last_heartbeat'), table_name='runners')
    op.drop_index(op.f('ix_runners_enabled'), table_name='runners')
    op.drop_table('runners')
    op.drop_index(op.f('ix_repositories_name'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_active'), table_name='repositories')
    op.drop_table('repositories')
    # ### end Alembic commands ###
